In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.__version__

'0.22.0'

In [19]:
df1 = pd.read_csv('C://Users//flang/Downloads//New_York_City_Population_By_Census_Tracts.csv')

In [12]:
import pandas as pd

In [20]:
df1

,Borough,Year,FIPS County Code,DCP Borough Code,Census Tract,Population
0,Bronx,2000,5,2,100,12780
1,Bronx,2000,5,2,200,3545
2,Bronx,2000,5,2,400,3314
3,Bronx,2000,5,2,1600,5237
4,Bronx,2000,5,2,1900,1584
5,Bronx,2000,5,2,2000,9068
6,Bronx,2000,5,2,2300,4338
7,Bronx,2000,5,2,2400,0
8,Bronx,2000,5,2,2500,5109
9,Bronx,2000,5,2,2701,3033
10,Bronx,2000,5,2,2702,4736
11,Bronx,2000,5,2,2800,5718
12,Bronx,2000,5,2,3100,1478
13,Bronx,2000,5,2,3300,3116
14,Bronx,2000,5,2,3500,3473
15,Bronx,2000,5,2,3700,478
16,Bronx,2000,5,2,3800,1263
17,Bronx,2000,5,2,3900,6022
18,Bronx,2000,5,2,4001,1420
19,Bronx,2000,5,2,4100,5240
20,Bronx,2000,5,2,4200,7539
21,Bronx,2000,5,2,4300,4789
22,Bronx,2000,5,2,4400,4671
23,Bronx,2000,5,2,4600,1419
24,Bronx,2000,5,2,4800,3678
25,Bronx,2000,5,2,5001,4871
26,Bronx,2000,5,2,5002,5869
27,Bronx,2000,5,2,5100,5634
28,Bronx,2000,5,2,5200,2186
29,Bronx,2000,5,2,5300,4159
...,...,...,...,...,...,...
4306,Staten Island,2010,85,5,20801,8977
4307,Staten Island,2010,85,5,20803,6463
4308,Staten Island,2010,85,5,20804,5323
4309,Staten Island,2010,85,5,21300,5376
4310,Staten Island,2010,85,5,22300,2880
4311,Staten Island,2010,85,5,22600,8490
4312,Staten Island,2010,85,5,22800,105
4313,Staten Island,2010,85,5,23100,4683
4314,Staten Island,2010,85,5,23900,3250
4315,Staten Island,2010,85,5,24401,5823
4316,Staten Island,2010,85,5,24402,4259
4317,Staten Island,2010,85,5,24700,2702
4318,Staten Island,2010,85,5,24800,4741
4319,Staten Island,2010,85,5,25100,5714
4320,Staten Island,2010,85,5,27301,3820
4321,Staten Island,2010,85,5,27302,3667
4322,Staten Island,2010,85,5,27702,6193
4323,Staten Island,2010,85,5,27704,4108
4324,Staten Island,2010,85,5,27705,5351
4325,Staten Island,2010,85,5,27706,2950
4326,Staten Island,2010,85,5,27900,2137
4327,Staten Island,2010,85,5,29102,2953
4328,Staten Island,2010,85,5,29103,7245
4329,Staten Island,2010,85,5,29104,6735
4330,Staten Island,2010,85,5,30301,4929
4331,Staten Island,2010,85,5,30302,6369
4332,Staten Island,2010,85,5,31901,3265
4333,Staten Island,2010,85,5,31902,4848
4334,Staten Island,2010,85,5,32300,1250
4335,Staten Island,2010,85,5,990100,0

In [21]:
df1.head()

  Borough  Year  FIPS County Code  DCP Borough Code  Census Tract  Population
0   Bronx  2000                 5                 2           100       12780
1   Bronx  2000                 5                 2           200        3545
2   Bronx  2000                 5                 2           400        3314
3   Bronx  2000                 5                 2          1600        5237
4   Bronx  2000                 5                 2          1900        1584

In [15]:
df = pd.read_csv('C://Users//flang//Downloads//Sacramentorealestatetransactions.csv')

In [16]:
pd.__version__

'0.22.0'

In [17]:
df

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,106250,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,106852,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,107502,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,108750,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,110700,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,113263,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,116250,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,120000,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,122682,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,123000,38.702792,-121.382210
23,9 PASTURE CT,SACRAMENTO,95834,CA,3,2,1601,Residential,Wed May 21 00:00:00 EDT 2008,124100,38.628631,-121.488097
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,125000,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,127281,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,129000,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,131200,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,132000,38.472122,-121.404199
...,...,...,...,...,...,...,...,...,...,...,...,...
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,208250,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,208318,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,209347,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,211500,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,216000,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,216021,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,219000,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,219794,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,220000,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.665104,-121.315901
968,1178 WARMWOOD CT,GALT,95632,CA,4,2,1770,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.289544,-121.284607
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,223000,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,224252,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,224500,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,225000,38.703056,-121.235221
975,5024 CHAMBERLIN CIR,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,228000,38.389756,-121.446246
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

In [22]:
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [24]:
import  os

In [26]:
print(os.getcwd())

#working direction

C:\Users\flang

In [31]:
#numbers of rows
len(df)

985

In [32]:
len(df1)

4336

In [33]:
len(df.columns)

12

In [34]:
len(df1.columns)

6

In [29]:
#se columns
df.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [30]:
df1.columns

Index(['Borough', 'Year', 'FIPS County Code', 'DCP Borough Code',
       'Census Tract', 'Population'],
      dtype='object')

In [36]:
df.head(7)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895,38.681659,-121.351705

In [37]:
df.tail()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
street       985 non-null object
city         985 non-null object
zip          985 non-null int64
state        985 non-null object
beds         985 non-null int64
baths        985 non-null int64
sq__ft       985 non-null int64
type         985 non-null object
sale_date    985 non-null object
price        985 non-null int64
latitude     985 non-null float64
longitude    985 non-null float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.4+ KB

In [41]:
df.describe()

,zip,beds,baths,sq__ft,price,latitude,longitude
count,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000
mean,95750.697462,2.911675,1.776650,1314.916751,234144.263959,38.607732,-121.355982
std,85.176072,1.307932,0.895371,853.048243,138365.839085,0.145433,0.138278
min,95603.000000,0.000000,0.000000,0.000000,1551.000000,38.241514,-121.551704
25%,95660.000000,2.000000,1.000000,952.000000,145000.000000,38.482717,-121.446127
50%,95762.000000,3.000000,2.000000,1304.000000,213750.000000,38.626582,-121.376220
75%,95828.000000,4.000000,2.000000,1718.000000,300000.000000,38.695589,-121.295778
max,95864.000000,8.000000,5.000000,5822.000000,884790.000000,39.020808,-120.597599

In [43]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
zip,985.0,95750.697462,85.176072,95603.000000,95660.000000,95762.000000,95828.000000,95864.000000
beds,985.0,2.911675,1.307932,0.000000,2.000000,3.000000,4.000000,8.000000
baths,985.0,1.776650,0.895371,0.000000,1.000000,2.000000,2.000000,5.000000
sq__ft,985.0,1314.916751,853.048243,0.000000,952.000000,1304.000000,1718.000000,5822.000000
price,985.0,234144.263959,138365.839085,1551.000000,145000.000000,213750.000000,300000.000000,884790.000000
latitude,985.0,38.607732,0.145433,38.241514,38.482717,38.626582,38.695589,39.020808
longitude,985.0,-121.355982,0.138278,-121.551704,-121.446127,-121.376220,-121.295778,-120.597599

In [44]:
#### REnaming columns of a Dataframe

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('C://Users//flang//Downloads//Sacramentorealestatetransactions.csv')

In [8]:
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [9]:
df[200:205]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
200,4660 CEDARWOOD WAY,SACRAMENTO,95823,CA,4,2,1310,Residential,Tue May 20 00:00:00 EDT 2008,150000,38.484834,-121.449316
201,9254 HARROGATE WAY,ELK GROVE,95758,CA,2,2,1006,Residential,Tue May 20 00:00:00 EDT 2008,152000,38.420138,-121.412179
202,6716 TAREYTON WAY,CITRUS HEIGHTS,95621,CA,3,2,1104,Residential,Tue May 20 00:00:00 EDT 2008,156000,38.693724,-121.307169
203,2028 ROBERT WAY,SACRAMENTO,95825,CA,2,1,810,Residential,Tue May 20 00:00:00 EDT 2008,156000,38.609982,-121.419263
204,9346 AIZENBERG CIR,ELK GROVE,95624,CA,2,2,1123,Residential,Tue May 20 00:00:00 EDT 2008,156000,38.418750,-121.370019

In [10]:
len(df)

985

In [11]:
df[980:]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

In [12]:
df[:3]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839

In [23]:
df[: : -1].head(10)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.417382,-121.484325
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.445342,-121.441504
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500,38.467936,-121.445477
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027,38.897814,-121.324691
975,5024 CHAMBERLIN CIR,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,228000,38.389756,-121.446246

In [15]:
df[::200]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
200,4660 CEDARWOOD WAY,SACRAMENTO,95823,CA,4,2,1310,Residential,Tue May 20 00:00:00 EDT 2008,150000,38.484834,-121.449316
400,117 EVCAR WAY,RIO LINDA,95673,CA,3,2,1182,Residential,Mon May 19 00:00:00 EDT 2008,164000,38.687659,-121.463300
600,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
800,1214 DAWNWOOD DR,GALT,95632,CA,3,2,1548,Residential,Fri May 16 00:00:00 EDT 2008,328370,38.290119,-121.286023

In [16]:
df.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [22]:
df['street'].head(10)

0                       3526 HIGH ST
1                        51 OMAHA CT
2                     2796 BRANCH ST
3                   2805 JANETTE WAY
4                    6001 MCMAHON DR
5                 5828 PEPPERMILL CT
6                6048 OGDEN NASH WAY
7                      2561 19TH AVE
8    11150 TRINITY RIVER DR Unit 114
9                       7325 10TH ST
Name: street, dtype: object

In [24]:
['street', 'city', 'zip']

['street', 'city', 'zip']

In [25]:
df[['street', 'city', 'zip']].head(10)

                            street            city    zip
0                     3526 HIGH ST      SACRAMENTO  95838
1                      51 OMAHA CT      SACRAMENTO  95823
2                   2796 BRANCH ST      SACRAMENTO  95815
3                 2805 JANETTE WAY      SACRAMENTO  95815
4                  6001 MCMAHON DR      SACRAMENTO  95824
5               5828 PEPPERMILL CT      SACRAMENTO  95841
6              6048 OGDEN NASH WAY      SACRAMENTO  95842
7                    2561 19TH AVE      SACRAMENTO  95820
8  11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  95670
9                     7325 10TH ST       RIO LINDA  95673

In [27]:
['state','city', 'street''zip', 'beds']

['state', 'city', 'streetzip', 'beds']

In [29]:
df[['state','city', 'street','zip', 'beds']].head(5)

  state        city            street    zip  beds
0    CA  SACRAMENTO      3526 HIGH ST  95838     2
1    CA  SACRAMENTO       51 OMAHA CT  95823     3
2    CA  SACRAMENTO    2796 BRANCH ST  95815     2
3    CA  SACRAMENTO  2805 JANETTE WAY  95815     2
4    CA  SACRAMENTO   6001 MCMAHON DR  95824     2

In [30]:
df.city.head(5)

0    SACRAMENTO
1    SACRAMENTO
2    SACRAMENTO
3    SACRAMENTO
4    SACRAMENTO
Name: city, dtype: object

In [35]:
df.zip.head(6)

0    95838
1    95823
2    95815
3    95815
4    95824
5    95841
Name: zip, dtype: int64

In [40]:
df[290:297][['street', 'city', 'zip', 'state']]

                street            city    zip state
290      106 FARHAM DR          FOLSOM  95630    CA
291    5405 NECTAR CIR       ELK GROVE  95757    CA
292      5411 10TH AVE      SACRAMENTO  95820    CA
293  3512 RAINSONG CIR  RANCHO CORDOVA  95670    CA
294       1106 55TH ST      SACRAMENTO  95819    CA
295    411 ILLSLEY WAY          FOLSOM  95630    CA
296  796 BUTTERCUP CIR            GALT  95632    CA

In [38]:
df.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [41]:
df.head(2)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028

In [43]:
answ=df.price*df.beds

In [45]:
answ.head(3)

0    118444
1    204636
2    137760
dtype: int64

In [46]:
df['Power']=df.price*df.beds

In [48]:
df.head(5)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,Power
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879,118444
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028,204636
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839,137760
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146,138614
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768,163800

In [52]:
df.drop('Power',1).head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [51]:
df.head(3)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,Power
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879,118444
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028,204636
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839,137760

In [53]:
df=df.drop('Power',1)

In [54]:
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [58]:
df.price<69308

0       True
1       True
2       True
3       True
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
955    False
956    False
957    False
958    False
959    False
960    False
961    False
962    False
963    False
964    False
965    False
966    False
967    False
968    False
969    False
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
Name: price, Length: 985, dtype: bool

In [59]:
filter=df.price<69308

In [60]:
df[filter]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
158,6272 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Tue May 20 00:00:00 EDT 2008,69000,38.680923,-121.313945
335,5840 WALERGA RD,SACRAMENTO,95842,CA,2,1,840,Condo,Mon May 19 00:00:00 EDT 2008,40000,38.673678,-121.357471
336,923 FULTON AVE,SACRAMENTO,95825,CA,1,1,484,Condo,Mon May 19 00:00:00 EDT 2008,48000,38.582279,-121.401482
337,261 REDONDO AVE,SACRAMENTO,95815,CA,3,1,970,Residential,Mon May 19 00:00:00 EDT 2008,61500,38.620685,-121.460539
338,4030 BROADWAY,SACRAMENTO,95817,CA,2,1,623,Residential,Mon May 19 00:00:00 EDT 2008,62050,38.546798,-121.460038
339,3660 22ND AVE,SACRAMENTO,95820,CA,2,1,932,Residential,Mon May 19 00:00:00 EDT 2008,65000,38.532718,-121.467470
340,3924 HIGH ST,SACRAMENTO,95838,CA,2,1,796,Residential,Mon May 19 00:00:00 EDT 2008,65000,38.638797,-121.435049
341,4734 14TH AVE,SACRAMENTO,95820,CA,2,1,834,Residential,Mon May 19 00:00:00 EDT 2008,68000,38.539447,-121.450858
342,4734 14TH AVE,SACRAMENTO,95820,CA,2,1,834,Residential,Mon May 19 00:00:00 EDT 2008,68000,38.539447,-121.450858
554,20 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885327,-121.289412
555,24 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885132,-121.289405
556,28 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884936,-121.289397
557,32 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884741,-121.289390
558,36 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884599,-121.289406
559,40 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884535,-121.289619
560,44 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884590,-121.289835
561,48 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884667,-121.289896
562,52 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884780,-121.289911
563,68 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885236,-121.289928
564,72 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885350,-121.289926
565,76 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885464,-121.289922
566,80 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885578,-121.289919
567,84 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885692,-121.289915
568,88 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885806,-121.289911
569,92 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885920,-121.289908
570,96 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886024,-121.289859
...,...,...,...,...,...,...,...,...,...,...,...,...
588,100 CRYSTALWOOD WAY,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886282,-121.289706
589,55 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884865,-121.289922
590,51 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884752,-121.289907
591,47 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884638,-121.289893
592,43 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884568,-121.289784
593,39 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884546,-121.289562
594,35 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884645,-121.289397
595,31 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884790,-121.289392
596,27 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884985,-121.289399
597,23 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885181,-121.289406
598,19 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885376,-121.289414
599,15 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885571,-121.289421
600,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
601,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
602,3 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886093,-121.289584
603,8208 WOODYARD WAY,CITRUS HEIGHTS,95621,CA,3,2,1166,Residential,Fri May 16 00:00:00 EDT 2008,30000,38.715322,-121.314787
604,113 RINETTI WAY,RIO LINDA,95673,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,30000,38.687172,-121.463933
605,15 LOORZ CT,SACRAMENTO,95823,CA,2,1,838,Residential,Fri May 16 00:00:00 EDT 2008,55422,38.471646,-121.435158
606,5805 DOTMAR WAY,NORTH HIGHLANDS,95660,CA,2,1,904,Residential,Fri May 16 00:00:00 EDT 2008,63000,38.672642,-121.380343
607,2332 CAMBRIDGE ST,SACRAMENTO,95815,CA,2,1,1032,Residential,Fri May 16 00:00:00 EDT 2008,65000,38.608085,-121.449651
608,3812 BELDEN ST,SACRAMENTO,95838,CA,2,1,904,Residential,Fri May 16 00:00:00 EDT 2008,65000,38.636833,-121.441640
609,3348 40TH ST,SACRAMENTO,95817,CA,2,1,1080,Residential,Fri May 16 00:00:00 EDT 2008,65000,38.544162,-121.460652
610,127 QUASAR CIR,SACRAMENTO,95822,CA,2,2,990,Residential,Fri May 16 00:00:00 EDT 2008,66500,38.493504,-121.475304
865,3720 VISTA DE MADERA,LINCOLN,95648,CA,3,3,0,Residential,Fri May 16 00:00:00 EDT 2008,1551,38.851645,-121.231742
866,14151 INDIO DR,SLOUGHHOUSE,95683,CA,3,4,5822,Residential,Fri May 16 00:00:00 EDT 2008,2000,38.490447,-121.129337
867,7401 TOULON LN,SACRAMENTO,95828,CA,4,2,1512,Residential,Thu May 15 00:00:00 EDT 2008,56950,38.488628,-121.387759
868,9127 NEWHALL DR Unit 34,SACRAMENTO,95826,CA,1,1,611,Condo,Thu May 15 00:00:00 EDT 2008,60000,38.542419,-121.359904
869,5937 BAMFORD DR,SACRAMENTO,95823,CA,2,1,876,Residential,Thu May 15 00:00:00 EDT 2008,61000,38.471139,-121.432255
870,5672 HILLSDALE BLVD,SACRAMENTO,95842,CA,2,1,933,Condo,Thu May 15 00:00:00 EDT 2008,62000,38.670467,-121.359799
871,3920 39TH ST,SACRAMENTO,95820,CA,2,1,864,Residential,Thu May 15 00:00:00 EDT 2008,68566,38.539213,-121.463930

In [63]:
df[df.beds<1]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
73,17 SERASPI CT,SACRAMENTO,95834,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,206000,38.631481,-121.501880
89,2866 KARITSA AVE,SACRAMENTO,95833,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,244500,38.626671,-121.525970
100,12209 CONSERVANCY WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,263500,38.553867,-121.219141
121,5337 DUSTY ROSE WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,320000,38.528575,-121.228600
126,2115 SMOKESTACK WAY,SACRAMENTO,95833,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,339500,38.602416,-121.542965
133,8082 LINDA ISLE LN,SACRAMENTO,95831,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,370000,38.477200,-121.521500
147,9278 DAIRY CT,ELK GROVE,95624,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,445000,38.420338,-121.363757
153,868 HILDEBRAND CIR,FOLSOM,95630,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,585000,38.670947,-121.097727
169,14788 NATCHEZ CT,RANCHO MURIETA,95683,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,97750,38.492287,-121.100032
192,5201 LAGUNA OAKS DR Unit 126,ELK GROVE,95758,CA,0,0,0,Condo,Tue May 20 00:00:00 EDT 2008,145000,38.423251,-121.444489
234,3139 SPOONWOOD WAY Unit 1,SACRAMENTO,95833,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,215500,38.626582,-121.521510
236,2340 HURLEY WAY,SACRAMENTO,95825,CA,0,0,0,Condo,Tue May 20 00:00:00 EDT 2008,225000,38.588816,-121.408549
248,611 BLOSSOM ROCK LN,FOLSOM,95630,CA,0,0,0,Condo,Tue May 20 00:00:00 EDT 2008,240000,38.645700,-121.119700
249,8830 ADUR RD,ELK GROVE,95624,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,242000,38.437420,-121.372876
253,221 PICASSO CIR,SACRAMENTO,95835,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,250000,38.676658,-121.528128
265,230 BANKSIDE WAY,SACRAMENTO,95835,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,270000,38.676937,-121.529244
268,4236 ADRIATIC SEA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,270000,38.647961,-121.543162
279,11281 STANFORD COURT LN Unit 604,GOLD RIVER,95670,CA,0,0,0,Condo,Tue May 20 00:00:00 EDT 2008,300000,38.625289,-121.260286
285,3224 PARKHAM DR,ROSEVILLE,95747,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,306500,38.772771,-121.364877
286,15 VANESSA PL,SACRAMENTO,95835,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,312500,38.668692,-121.545490
308,5404 ALMOND FALLS WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,425000,38.527502,-121.233492
310,14 CASA VATONI PL,SACRAMENTO,95834,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,433500,38.650221,-121.551704
324,201 FIRESTONE DR,ROSEVILLE,95678,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,500500,38.770153,-121.300039
326,2733 DANA LOOP,EL DORADO HILLS,95762,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,541000,38.628459,-121.055078
327,9741 SADDLEBRED CT,WILTON,95693,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,560000,38.408841,-121.198039
469,8491 CRYSTAL WALK CIR,ELK GROVE,95758,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,261000,38.416916,-121.407554
477,6286 LONETREE BLVD,ROCKLIN,95765,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,274500,38.805036,-121.293608
494,3072 VILLAGE PLAZA DR,ROSEVILLE,95747,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,307000,38.773094,-121.365905
503,12241 CANYONLANDS DR,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,331500,38.557293,-121.217611
505,907 RIO ROBLES AVE,SACRAMENTO,95838,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,344755,38.664765,-121.445006
...,...,...,...,...,...,...,...,...,...,...,...,...
600,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
601,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
602,3 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886093,-121.289584
604,113 RINETTI WAY,RIO LINDA,95673,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,30000,38.687172,-121.463933
686,5890 TT TRAK,FORESTHILL,95631,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,194818,39.020808,-120.821518
718,9967 HATHERTON WAY,ELK GROVE,95757,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,222500,38.305200,-121.403300
737,3569 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,247000,38.631139,-121.501879
743,6288 LONETREE BLVD,ROCKLIN,95765,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,250000,38.804993,-121.293609
754,6001 SHOO FLY RD,PLACERVILLE,95667,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,270000,38.813546,-120.809254
755,3040 PARKHAM DR,ROSEVILLE,95747,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,271000,38.770835,-121.366996
757,6007 MARYBELLE LN,SHINGLE SPRINGS,95682,CA,0,0,0,Unkown,Fri May 16 00:00:00 EDT 2008,275000,38.643470,-120.888183
774,8253 KEEGAN WAY,ELK GROVE,95624,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,298000,38.446286,-121.400817
789,5222 COPPER SUNSET WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,313000,38.529181,-121.224755
798,3232 PARKHAM DR,ROSEVILLE,95747,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,325500,38.772821,-121.364821
819,2274 IVY BRIDGE DR,ROSEVILLE,95747,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,375000,38.778561,-121.362008
823,201 KIRKLAND CT,LINCOLN,95648,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,389000,38.867125,-121.319085
824,12075 APPLESBURY CT,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,390000,38.535700,-121.224900
826,5420 ALMOND FALLS WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,396000,38.527384,-121.233531
828,1515 EL CAMINO VERDE DR,LINCOLN,95648,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,400000,38.904869,-121.320750
836,1536 STONEY CROSS LN,LINCOLN,95648,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,433500,38.860007,-121.310946
848,200 HILLSFORD CT,ROSEVILLE,95747,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,511000,38.780051,-121.378718
859,4478 GREENBRAE RD,ROCKLIN,95677,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.781134,-121.222801
861,200 CRADLE MOUNTAIN CT,EL DORADO HILLS,95762,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,622500,38.647800,-121.030900
862,2065 IMPRESSIONIST WAY,EL DORADO HILLS,95762,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,680000,38.682961,-121.033253
888,3035 ESTEPA DR Unit 5C,CAMERON PARK,95682,CA,0,0,0,Condo,Thu May 15 00:00:00 EDT 2008,119000,38.681393,-120.996713
901,1530 TOPANGA LN Unit 204,LINCOLN,95648,CA,0,0,0,Condo,Thu May 15 00:00:00 EDT 2008,138000,38.884150,-121.270277
917,501 POPLAR AVE,WEST SACRAMENTO,95691,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,165000,38.584526,-121.534609
934,1550 TOPANGA LN Unit 207,LINCOLN,95648,CA,0,0,0,Condo,Thu May 15 00:00:00 EDT 2008,188000,38.884170,-121.270222
947,1525 PENNSYLVANIA AVE,WEST SACRAMENTO,95691,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,200100,38.569943,-121.527539
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.631026,-121.501879

In [70]:
sub10=df[::10]

In [71]:
sub10

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309,38.637663,-121.451520
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000,38.707851,-121.320707
30,5201 LAGUNA OAKS DR Unit 140,ELK GROVE,95758,CA,2,2,1039,Condo,Wed May 21 00:00:00 EDT 2008,133000,38.423251,-121.444489
40,4800 WESTLAKE PKWY Unit 2109,SACRAMENTO,95835,CA,2,2,1304,Condo,Wed May 21 00:00:00 EDT 2008,152000,38.658812,-121.542345
50,9417 SARA ST,ELK GROVE,95624,CA,3,2,1188,Residential,Wed May 21 00:00:00 EDT 2008,170000,38.415518,-121.370527
60,4844 CLYDEBANK WAY,ANTELOPE,95843,CA,3,2,1215,Residential,Wed May 21 00:00:00 EDT 2008,182716,38.714609,-121.347887
70,8708 MESA BROOK WAY,ELK GROVE,95624,CA,4,2,1715,Residential,Wed May 21 00:00:00 EDT 2008,199500,38.440760,-121.385792
80,5037 J PKWY,SACRAMENTO,95823,CA,3,2,1478,Residential,Wed May 21 00:00:00 EDT 2008,231477,38.491399,-121.443547
90,6913 RICHEVE WAY,SACRAMENTO,95828,CA,3,1,958,Residential,Wed May 21 00:00:00 EDT 2008,244960,38.502519,-121.420769
100,12209 CONSERVANCY WAY,RANCHO CORDOVA,95742,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,263500,38.553867,-121.219141
110,8882 AUTUMN GOLD CT,ELK GROVE,95624,CA,4,2,1993,Residential,Wed May 21 00:00:00 EDT 2008,287417,38.443900,-121.372550
120,4359 CREGAN CT,RANCHO CORDOVA,95742,CA,5,4,3516,Residential,Wed May 21 00:00:00 EDT 2008,320000,38.545128,-121.224922
130,6708 PONTA DO SOL WAY,ELK GROVE,95757,CA,4,2,3134,Residential,Wed May 21 00:00:00 EDT 2008,347650,38.380635,-121.425538
140,1300 F ST,SACRAMENTO,95814,CA,3,3,1627,Residential,Wed May 21 00:00:00 EDT 2008,391000,38.583550,-121.487289
150,7004 RAWLEY WAY,ELK GROVE,95757,CA,4,3,3440,Residential,Wed May 21 00:00:00 EDT 2008,489332,38.406421,-121.422081
160,9512 EMERALD PARK DR Unit 3,ELK GROVE,95624,CA,2,1,840,Condo,Tue May 20 00:00:00 EDT 2008,71000,38.405730,-121.369832
170,1069 ACACIA AVE,SACRAMENTO,95815,CA,2,1,1220,Residential,Tue May 20 00:00:00 EDT 2008,98000,38.621998,-121.442238
180,211 MCDANIEL CIR,SACRAMENTO,95838,CA,3,2,1110,Residential,Tue May 20 00:00:00 EDT 2008,123750,38.636565,-121.460383
190,5333 PRIMROSE DR Unit 19A,FAIR OAKS,95628,CA,2,2,994,Condo,Tue May 20 00:00:00 EDT 2008,142500,38.662785,-121.276272
200,4660 CEDARWOOD WAY,SACRAMENTO,95823,CA,4,2,1310,Residential,Tue May 20 00:00:00 EDT 2008,150000,38.484834,-121.449316
210,4500 TIPPWOOD WAY,SACRAMENTO,95842,CA,3,2,1159,Residential,Tue May 20 00:00:00 EDT 2008,169000,38.699510,-121.359989
220,7031 CANEVALLEY CIR,CITRUS HEIGHTS,95621,CA,3,2,1137,Residential,Tue May 20 00:00:00 EDT 2008,194000,38.718693,-121.303619
230,3361 BOW MAR CT,CAMERON PARK,95682,CA,2,2,0,Residential,Tue May 20 00:00:00 EDT 2008,210000,38.694370,-120.996602
240,9257 CALDERA WAY,SACRAMENTO,95826,CA,4,2,1605,Residential,Tue May 20 00:00:00 EDT 2008,228000,38.558210,-121.355022
250,7344 BUTTERBALL WAY,SACRAMENTO,95842,CA,3,2,1503,Residential,Tue May 20 00:00:00 EDT 2008,245000,38.699489,-121.361828
260,7922 MANSELL WAY,ELK GROVE,95758,CA,4,2,1595,Residential,Tue May 20 00:00:00 EDT 2008,260000,38.409634,-121.410787
270,9455 SEA CLIFF WAY,ELK GROVE,95758,CA,4,2,2056,Residential,Tue May 20 00:00:00 EDT 2008,275000,38.411522,-121.481406
280,7320 6TH ST,RIO LINDA,95673,CA,3,1,1284,Residential,Tue May 20 00:00:00 EDT 2008,300000,38.700553,-121.452223
290,106 FARHAM DR,FOLSOM,95630,CA,3,2,1258,Residential,Tue May 20 00:00:00 EDT 2008,330000,38.667834,-121.168578
...,...,...,...,...,...,...,...,...,...,...,...,...
690,2561 VERNA WAY,SACRAMENTO,95821,CA,3,1,1473,Residential,Fri May 16 00:00:00 EDT 2008,195000,38.611055,-121.369964
700,7901 GAZELLE TRAIL WAY,ANTELOPE,95843,CA,4,2,1953,Residential,Fri May 16 00:00:00 EDT 2008,207744,38.711740,-121.342675
710,1528 HESKET WAY,SACRAMENTO,95825,CA,4,2,1566,Residential,Fri May 16 00:00:00 EDT 2008,220000,38.593598,-121.403637
720,320 GROTH CIR,SACRAMENTO,95834,CA,3,2,1441,Residential,Fri May 16 00:00:00 EDT 2008,225000,38.638882,-121.531883
730,9297 TROUT WAY,ELK GROVE,95624,CA,4,2,2367,Residential,Fri May 16 00:00:00 EDT 2008,240000,38.420637,-121.375798
740,9247 DELAIR WAY,ELK GROVE,95758,CA,4,3,1899,Residential,Fri May 16 00:00:00 EDT 2008,249000,38.422241,-121.458022
750,2298 PRIMROSE LN,LINCOLN,95648,CA,3,2,1621,Residential,Fri May 16 00:00:00 EDT 2008,260000,38.899180,-121.322514
760,2678 BRIARTON DR,LINCOLN,95648,CA,3,2,1650,Residential,Fri May 16 00:00:00 EDT 2008,276500,38.844116,-121.274806
770,1524 YOUNGS AVE,SACRAMENTO,95838,CA,4,2,1382,Residential,Fri May 16 00:00:00 EDT 2008,293996,38.644927,-121.430540
780,5776 TERRACE DR,ROCKLIN,95765,CA,3,2,1577,Residential,Fri May 16 00:00:00 EDT 2008,300567,38.800539,-121.260979
790,5601 SPINDRIFT LN,ORANGEVALE,95662,CA,4,2,2004,Residential,Fri May 16 00:00:00 EDT 2008,315000,38.668289,-121.192316
800,1214 DAWNWOOD DR,GALT,95632,CA,3,2,1548,Residential,Fri May 16 00:00:00 EDT 2008,328370,38.290119,-121.286023
810,4821 HUTSON WAY,ELK GROVE,95757,CA,5,3,2877,Residential,Fri May 16 00:00:00 EDT 2008,349000,38.386239,-121.448159
820,14004 WALNUT AVE,WALNUT GROVE,95690,CA,3,1,1727,Residential,Fri May 16 00:00:00 EDT 2008,380000,38.247659,-121.515129
830,1792 DIAMOND WOODS CIR,ROSEVILLE,95747,CA,4,3,0,Residential,Fri May 16 00:00:00 EDT 2008,412500,38.808581,-121.327850
840,1113 SANDWICK WAY,FOLSOM,95630,CA,4,3,3261,Residential,Fri May 16 00:00:00 EDT 2008,446000,38.673882,-121.105077
850,4841 VILLAGE GREEN DR,EL DORADO HILLS,95762,CA,4,3,0,Residential,Fri May 16 00:00:00 EDT 2008,533000,38.664066,-121.056735
860,8432 BRIGGS DR,ROSEVILLE,95747,CA,5,3,3579,Residential,Fri May 16 00:00:00 EDT 2008,610000,38.788610,-121.339495
870,5672 HILLSDALE BLVD,SACRAMENTO,95842,CA,2,1,933,Condo,Thu May 15 00:00:00 EDT 2008,62000,38.670467,-121.359799
880,6208 GRATTAN WAY,NORTH HIGHLANDS,95660,CA,3,1,1051,Residential,Thu May 15 00:00:00 EDT 2008,105000,38.679279,-121.376615
890,7730 ROBINETTE RD,SACRAMENTO,95828,CA,3,2,1269,Residential,Thu May 15 00:00:00 EDT 2008,122000,38.477090,-121.410569
900,2636 TRONERO WAY,RANCHO CORDOVA,95670,CA,3,1,1000,Residential,Thu May 15 00:00:00 EDT 2008,134000,38.593049,-121.303040
910,8636 LONGSPUR WAY,ANTELOPE,95843,CA,3,2,1670,Residential,Thu May 15 00:00:00 EDT 2008,157296,38.725873,-121.358560
920,1001 RIO NORTE WAY,SACRAMENTO,95834,CA,3,2,1202,Residential,Thu May 15 00:00:00 EDT 2008,169000,38.634292,-121.485106
930,1140 EDMONTON DR,SACRAMENTO,95833,CA,3,2,1204,Residential,Thu May 15 00:00:00 EDT 2008,174250,38.624570,-121.486913
940,6601 WOODMORE OAKS DR,ORANGEVALE,95662,CA,3,2,1294,Residential,Thu May 15 00:00:00 EDT 2008,191250,38.687006,-121.254319
950,6600 SILVERTHORNE CIR,SACRAMENTO,95842,CA,4,3,1968,Residential,Thu May 15 00:00:00 EDT 2008,205000,38.686070,-121.342369
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000,38.467836,-121.410366
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.631026,-121.501879
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620

In [73]:
sub10.iat[10,2]

95742